name: Execução de testes regressivos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Executa nos minutos 0, 10 e 15 de cada hora, de segunda a sexta
    - cron: '0,10,15 * * * 1-5' 

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout projeto
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Definido uma versão fixa ou adicione uma matrix

      - name: Install dependencies
        run: npm install

      - name: Setup Cypress
        uses: cypress-io/github-action@v6
       
      - name: Run CodeceptJS tests
        run: npx codeceptjs run
